theme: jekyll-theme-architect
title: Aox Linux
description: Una Distribución Rápida y Sencilla
google_analytics: G-Q4GGGMKM82
show_downloads: true
github:
  iso_url: https://github.com/aoxlinux/aoxlinux/releases/download/v0.1-beta/aoxlinux-2022.02.13_v0_1-x86_64.iso
